services:
  fixer:
    build: .
    volumes:
      - .:/app
    environment:
      PHP_CS_FIXER_IGNORE_ENV: "1"
      PHP_CS_FIXER_VERSION: v3.95.21
      PHP_CS_FIXER_PHAR: /opt/php-cs-fixer/php-cs-fixer
      CONFIG_FILE: tests/fixtures/.php-cs-fixer.dist.php
      CONFIG_PATH: tests/fixtures/.php-cs-fixer.dist.php
