name: Bug report
description: Create a report to help us improve
title: "Bug: "
labels: ['type: Bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you begin, **please ensure that there are no [existing issues](https://github.com/ale94lko/php-cs-fixer-action/issues), whether still open or closed, related to your report**.
        If there is, your report will be closed promptly.
        ---

  - type: input
    id: php-cs-fixer-version
    attributes:
      label: php-cs-fixer version
      description: |
        e.g. v3.9.4
        If you are not using the [latest version](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases), please
        check to see if the problem occurs with the latest version.
    validations:
      required: true

  - type: dropdown
    id: rules-version
    attributes:
      label: Rules version
      description: Which php-cs-fixer-rules version did you run your code?
      multiple: true
      options:
        - 'Default'
        - 'v1.0'
        - 'v1.0.1'
    validations:
      required: true

  - type: dropdown
    id: full-rules-version
    attributes:
      label: Full or minimal rules version
      description: Which rules package did you run your code?
      multiple: true
      options:
        - 'Default'
        - 'Full rules package'
        - 'Minimal rules package'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Output
      description: What do you expect to happen instead of this bug?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false