blank_issues_enabled: false
contact_links:
  - name: Contributing guide
    url: https://github.com/ale94lko/php-cs-fixer-action/blob/main/CONTRIBUTING.md
    about: Read how to fork, test, and submit a pull request.
