name: Feature Request
description: Suggest an idea for this project
title: "Feature: "
labels: ['type: New Feature']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new feature report!

        Before you begin, **please ensure that there are no [existing issues](https://github.com/ale94lko/php-cs-fixer-action/issues), whether still open or closed, related to your report**.
        If there is, your report will be closed promptly.
        ---

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ale94lko/php-cs-fixer-action/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: eg. email@example.com
    validations:
      required: false

  - type: textarea
    attributes:
      label: What do you have in mind to make this project better?
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false